FROM rust:1.89-bookworm AS builder

ENV CARGO_BUILD_JOBS=1

RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        clang \
        cmake \
        libclang-dev \
        libpq-dev \
        libprotobuf-dev \
        libssl-dev \
        pkg-config \
        protobuf-compiler && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /build
COPY . .

RUN cargo build \
    --locked \
    --release \
    --package chirpstack \
    --no-default-features \
    --features postgres

FROM debian:bookworm-slim

RUN apt-get update && \
    apt-get install --yes --no-install-recommends \
        ca-certificates \
        libpq5 && \
    rm -rf /var/lib/apt/lists/*

COPY --from=builder /build/target/release/chirpstack /usr/bin/chirpstack

USER nobody:nogroup
ENTRYPOINT ["/usr/bin/chirpstack"]
